/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesCadastro;

import Classes.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TURUGO
 */
public class CadastroUsuario extends javax.swing.JFrame {
    private boolean editar =false;
    private boolean excluir = false;
    private int linhaSel;
    private char senha;
    private String sEnha;
    boolean verificarSenha;
    
    
    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
        
        DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();
        senha = txtPasswSenha.getEchoChar();
        
        for (int i = 0; i < Usuario.usuario.size(); i++) {
            dtm.addRow(new Object[]{Usuario.usuario.get(i).getNome(),Usuario.usuario.get(i).getLogin()});
        }
        btnConfirmar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDigitesenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtPasswConfirmarSenha = new javax.swing.JPasswordField();
        txtPasswSenha = new javax.swing.JPasswordField();
        lblOlhoConfirmarS = new javax.swing.JLabel();
        lblOlhoSenha = new javax.swing.JLabel();
        checkboxMostrarS = new javax.swing.JCheckBox();
        checkboxMostrarSenhaConfirmarS = new javax.swing.JCheckBox();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Usuário");
        setResizable(false);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pencil.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/disk.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Eliminar.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Login"
            }
        ));
        tableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableUsuariosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableUsuarios);

        txtNome.setEnabled(false);

        jLabel1.setText("Nome:");

        jLabel3.setText("Login");

        lblDigitesenha.setText("Digite uma senha:");

        txtLogin.setEnabled(false);

        jLabel5.setText("Confirme sua senha:");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtPasswConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPasswConfirmarSenha.setEnabled(false);
        txtPasswConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswConfirmarSenhaActionPerformed(evt);
            }
        });

        txtPasswSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPasswSenha.setEnabled(false);
        txtPasswSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswSenhaActionPerformed(evt);
            }
        });

        lblOlhoConfirmarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exibirSenha.png"))); // NOI18N

        lblOlhoSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exibirSenha.png"))); // NOI18N

        checkboxMostrarS.setText("Mostrar Senha");
        checkboxMostrarS.setEnabled(false);
        checkboxMostrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxMostrarSActionPerformed(evt);
            }
        });

        checkboxMostrarSenhaConfirmarS.setText("Mostrar Senha");
        checkboxMostrarSenhaConfirmarS.setEnabled(false);
        checkboxMostrarSenhaConfirmarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxMostrarSenhaConfirmarSActionPerformed(evt);
            }
        });

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lampada.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setEnabled(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOlhoSenha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkboxMostrarS))
                                    .addComponent(jLabel1)
                                    .addComponent(lblDigitesenha)
                                    .addComponent(txtPasswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(txtLogin)
                                        .addComponent(txtPasswConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOlhoConfirmarS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkboxMostrarSenhaConfirmarS))))
                            .addComponent(btnConfirmar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar)))
                        .addGap(0, 221, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(lblDigitesenha))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasswConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOlhoConfirmarS)
                    .addComponent(lblOlhoSenha)
                    .addComponent(checkboxMostrarS)
                    .addComponent(checkboxMostrarSenhaConfirmarS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmar)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtLogin.setText("");
        txtNome.setText("");
        txtPasswConfirmarSenha.setText("");
        txtPasswSenha.setText("");
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        checkboxMostrarS.setEnabled(true);
        checkboxMostrarSenhaConfirmarS.setEnabled(true);
        txtPasswConfirmarSenha.setEnabled(true);
        txtLogin.setEnabled(true);
        txtNome.setEnabled(true);
        txtPasswSenha.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnCancelar.setEnabled(true);
        tableUsuarios.setEnabled(false);
        tableUsuarios.setVisible(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String senhaTxt = new String(txtPasswSenha.getPassword());
        String CsenhaTxt = new String(txtPasswConfirmarSenha.getPassword());
        
        if(((senhaTxt.equals(""))||(txtLogin.getText().equals(""))||
        (txtNome.getText().equals(""))||(CsenhaTxt.equals("")))){
            JOptionPane.showMessageDialog(this, "Verificar campo em branco!");  
            
        }else{
            if(senhaTxt.equals(CsenhaTxt)==false){
                JOptionPane.showMessageDialog(this, "As senhas não correspondem!");
        
            }else{
                btnCancelar.setEnabled(false);
                btnNovo.setEnabled(true);
                btnEditar.setEnabled(false);
                btnSalvar.setEnabled(false);
                txtNome.setEnabled(false);
                txtPasswConfirmarSenha.setEnabled(false);
                txtLogin.setEnabled(false);
                txtPasswSenha.setEnabled(false);
                checkboxMostrarS.setEnabled(false);
                checkboxMostrarSenhaConfirmarS.setEnabled(false);


                String nome = txtNome.getText();
                String login = txtLogin.getText();
                String senhA = new String(txtPasswSenha.getPassword());
                
                if(editar ==true){
                    
                    int pos = tableUsuarios.getSelectedRow();
                    Usuario.usuario.get(pos).setNome(nome);
                    Usuario.usuario.get(pos).setSenha(senhA);
                    Usuario.usuario.get(pos).setLogin(login);
                    tableUsuarios.setValueAt(nome, pos, 0);
                    tableUsuarios.setValueAt(login, pos, 1);
                    checkboxMostrarS.setEnabled(false);
                    checkboxMostrarSenhaConfirmarS.setEnabled(false);
                    JOptionPane.showMessageDialog(null,"Dados alterados com sucesso!");
                    editar = false;

                }else{
                    Usuario usuario = new Usuario();

                    usuario.cadastrar(nome, senhA, login);
                    Usuario.usuario.add(usuario);
                    DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();

                    dtm.addRow(new Object[]{nome, login});

                    JOptionPane.showMessageDialog(null,"Dados cadastrados com sucesso!");
                    
                }
                
                txtNome.setText("");
                txtPasswConfirmarSenha.setText("");
                txtPasswSenha.setText("");
                txtLogin.setText("");
                tableUsuarios.setEnabled(true);
                tableUsuarios.setVisible(true);
            }

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        checkboxMostrarS.setEnabled(false);
        checkboxMostrarSenhaConfirmarS.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnConfirmar.setVisible(false);
        txtPasswConfirmarSenha.setEnabled(false);
        txtLogin.setEnabled(false);
        txtNome.setEnabled(false);
        txtPasswSenha.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnCancelar.setEnabled(false);
        tableUsuarios.setEnabled(true);
        tableUsuarios.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar=true;    
        btnNovo.setEnabled(false);
        btnConfirmar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(true);
        tableUsuarios.setEnabled(false); 
        tableUsuarios.setVisible(false);
        txtPasswSenha.setEnabled(true);
        lblOlhoSenha.setEnabled(true);
        checkboxMostrarS.setEnabled(true);
        lblDigitesenha.setText("Digite sua senha para editar:");
        btnConfirmar.setVisible(true);
    
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tableUsuariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuariosMouseReleased
        if(tableUsuarios.getSelectedRow() != -1){
            btnEditar.setEnabled(true);
            btnExcluir.setEnabled(true);
            
            linhaSel = tableUsuarios.getSelectedRow();
            
            txtNome.setText(Usuario.usuario.get(linhaSel).getNome());
            txtLogin.setText(Usuario.usuario.get(linhaSel).getLogin());
        }    
    }//GEN-LAST:event_tableUsuariosMouseReleased

    private void txtPasswConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswConfirmarSenhaActionPerformed
        
    }//GEN-LAST:event_txtPasswConfirmarSenhaActionPerformed

    private void txtPasswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswSenhaActionPerformed

    private void checkboxMostrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxMostrarSActionPerformed
        if (checkboxMostrarS.isSelected()){
            txtPasswSenha.setEchoChar('\u0000');
            lblOlhoSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ocultarSenha.png")));
        }else{
            txtPasswSenha.setEchoChar(senha);
            lblOlhoSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exibirSenha.png")));
        }
    }//GEN-LAST:event_checkboxMostrarSActionPerformed

    private void checkboxMostrarSenhaConfirmarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxMostrarSenhaConfirmarSActionPerformed
        if (checkboxMostrarSenhaConfirmarS.isSelected()){
            txtPasswConfirmarSenha.setEchoChar('\u0000');
            lblOlhoConfirmarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ocultarSenha.png")));
        }else{
            txtPasswConfirmarSenha.setEchoChar(senha);
            lblOlhoConfirmarS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exibirSenha.png")));
        }
    }//GEN-LAST:event_checkboxMostrarSenhaConfirmarSActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        sEnha = new String(txtPasswSenha.getPassword());

        if(sEnha.equals(Usuario.usuario.get(tableUsuarios.getSelectedRow()).getSenha())){
            
            if(excluir==true){
                if(JOptionPane.showConfirmDialog(null, "Deseja realmente exluir o registro?", "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
                    int RegistroSel = tableUsuarios.getSelectedRow();
                    DefaultTableModel dtm = (DefaultTableModel)tableUsuarios.getModel();
                    dtm.removeRow(RegistroSel);
                    tableUsuarios.setModel(dtm);
                    Usuario.usuario.remove(RegistroSel);
                    JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
                    txtPasswSenha.setEnabled(false);
                    lblOlhoSenha.setEnabled(false);
                    checkboxMostrarS.setEnabled(false);
                    lblDigitesenha.setText("Digite uma senha:");
                    btnConfirmar.setVisible(false);
                    btnNovo.setEnabled(true);
                    tableUsuarios.setEnabled(false);
                    txtLogin.setText("");
                    txtNome.setText("");
                    txtPasswConfirmarSenha.setText("");
                    txtPasswSenha.setText("");
                    tableUsuarios.setVisible(true);
                    tableUsuarios.setEnabled(true);
                }else{
                    txtPasswSenha.setEnabled(false);
                    lblOlhoSenha.setEnabled(false);
                    checkboxMostrarS.setEnabled(false);
                    lblDigitesenha.setText("Digite uma senha:");
                    btnConfirmar.setVisible(false);
                    btnNovo.setEnabled(true);
                    btnConfirmar.setEnabled(false);
                    btnCancelar.setEnabled(false);
                    tableUsuarios.setEnabled(false);
                    txtLogin.setText("");
                    txtNome.setText("");
                    txtPasswConfirmarSenha.setText("");
                    txtPasswSenha.setText("");
                    tableUsuarios.setVisible(true);
                    tableUsuarios.setEnabled(true);
                }
            
            }else{     
                editar = true;
                tableUsuarios.setEnabled(false);
                tableUsuarios.setVisible(true);
                lblOlhoConfirmarS.setEnabled(true);
                checkboxMostrarSenhaConfirmarS.setEnabled(true);
                txtPasswConfirmarSenha.setEnabled(true);
                txtLogin.setEnabled(true);
                txtNome.setEnabled(true);
                txtPasswSenha.setEnabled(true);
                btnSalvar.setEnabled(true);
                btnNovo.setEnabled(false);
                btnCancelar.setEnabled(true);
                btnEditar.setEnabled(false);
                btnConfirmar.setVisible(false);

            }
            
            txtPasswSenha.setText("");
            lblDigitesenha.setText("Digite uma senha:");
            txtPasswConfirmarSenha.setText("");
            txtPasswSenha.setText("");
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Senha inválida\n NÃO é possível realizar a ação");
            tableUsuarios.setVisible(true);
            tableUsuarios.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnNovo.setEnabled(true);
            txtPasswSenha.setEnabled(false);
            lblOlhoSenha.setEnabled(false);
            checkboxMostrarS.setEnabled(false);
            lblDigitesenha.setText("Digite uma senha:");
            btnConfirmar.setVisible(false);
            txtLogin.setText("");
            txtNome.setText("");
            txtPasswConfirmarSenha.setText("");
            txtPasswSenha.setText("");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir = true;
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        tableUsuarios.setVisible(false);
        tableUsuarios.setEnabled(false);
        btnNovo.setEnabled(false);
        btnConfirmar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(true);
        tableUsuarios.setEnabled(false);
        tableUsuarios.setVisible(false);
        
        txtPasswSenha.setEnabled(true);
        lblOlhoSenha.setEnabled(true);
        checkboxMostrarS.setEnabled(true);
        lblDigitesenha.setText("Digite sua senha excluir o usuário:");
        btnConfirmar.setVisible(true);
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox checkboxMostrarS;
    private javax.swing.JCheckBox checkboxMostrarSenhaConfirmarS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDigitesenha;
    private javax.swing.JLabel lblOlhoConfirmarS;
    private javax.swing.JLabel lblOlhoSenha;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtPasswConfirmarSenha;
    private javax.swing.JPasswordField txtPasswSenha;
    // End of variables declaration//GEN-END:variables
    
    public void recebendo(boolean veriFicarSenha){
        verificarSenha = veriFicarSenha;
    }

}
