/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OutrasInterfaces;

import Classes.Configuracao;
import javax.swing.JOptionPane;

/**
 *
 * @author TURUGO
 */
public class Configurações extends javax.swing.JFrame {

    /**
     * Creates new form Configurações
     */
    public Configurações() {
        initComponents();
        
        txtMensalidadeTitular.setText(Configuracao.getMensalidadeTitular()+"");
        txtMensalidadeDependente.setText(Configuracao.getTaxaDependente()+"");
        if(Configuracao.getTaxaDependente()!=0){
            txtMensalidadeDependente.setEnabled(true);
            radioBtnAdicionalDependente.setSelected(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnAdicionalDependente = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JButton();
        txtMensalidadeTitular = new javax.swing.JTextField();
        txtMensalidadeDependente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");
        setResizable(false);

        radioBtnAdicionalDependente.setText("Valor adicional por dependente?");
        radioBtnAdicionalDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnAdicionalDependenteActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/disk.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtMensalidadeTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensalidadeTitularActionPerformed(evt);
            }
        });
        txtMensalidadeTitular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMensalidadeTitularKeyPressed(evt);
            }
        });

        txtMensalidadeDependente.setEnabled(false);

        jLabel1.setText("Taxa dependente:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Moedas.png"))); // NOI18N
        jLabel2.setText("Valor mensalidade do Titular:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Configurações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBtnAdicionalDependente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMensalidadeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMensalidadeDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnSalvar)
                        .addGap(39, 39, 39)
                        .addComponent(btnCancelar)))
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMensalidadeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(radioBtnAdicionalDependente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMensalidadeDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(101, 101, 101)
                .addComponent(jLabel4)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtMensalidadeTitular.setText(Configuracao.getMensalidadeTitular()+"");
        txtMensalidadeDependente.setText(Configuracao.getTaxaDependente()+"");
        if(Configuracao.getTaxaDependente()==0){
            radioBtnAdicionalDependente.setSelected(false);
            txtMensalidadeDependente.setEnabled(false);
        }else{

            radioBtnAdicionalDependente.setSelected(true);
            txtMensalidadeDependente.setEnabled(true);
        }
        btnCancelar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
            try{
                Configuracao.setMensalidadeTitular(Float.parseFloat(txtMensalidadeTitular.getText()));

                if(radioBtnAdicionalDependente.isSelected()==false){
                    Configuracao.setTaxaDependente(0);
                }else{
                    if(txtMensalidadeDependente.getText().equals("0.0")){
                        radioBtnAdicionalDependente.setSelected(false);
                        txtMensalidadeDependente.setEnabled(false);
                        Configuracao.setTaxaDependente(0);
                    }else{
                        Configuracao.setTaxaDependente(Float.parseFloat(txtMensalidadeDependente.getText()));
                    }
                }

                JOptionPane.showMessageDialog(null, "Dados alterados com Sucesso!");
                txtMensalidadeTitular.setText(Configuracao.getMensalidadeTitular()+"");
                txtMensalidadeDependente.setText(Configuracao.getTaxaDependente()+"");

                if(Configuracao.getTaxaDependente()!=0){
                    txtMensalidadeDependente.setEnabled(true);
                    radioBtnAdicionalDependente.setSelected(true);
                }
                
                btnCancelar.setEnabled(false);
            }catch(NumberFormatException exception){
                JOptionPane.showMessageDialog(null, "Digite apenas valores no formato numérico\nEx: '10' ou '10.65' ");
            }

        
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void radioBtnAdicionalDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnAdicionalDependenteActionPerformed
        if(radioBtnAdicionalDependente.isSelected()==true){
            txtMensalidadeDependente.setEnabled(true);
            btnCancelar.setEnabled(true);
        }else{
            txtMensalidadeDependente.setEnabled(false);
            txtMensalidadeDependente.setText("0.0");
        }
    }//GEN-LAST:event_radioBtnAdicionalDependenteActionPerformed

    private void txtMensalidadeTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensalidadeTitularActionPerformed
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_txtMensalidadeTitularActionPerformed

    private void txtMensalidadeTitularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensalidadeTitularKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensalidadeTitularKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configurações().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton radioBtnAdicionalDependente;
    private javax.swing.JTextField txtMensalidadeDependente;
    private javax.swing.JTextField txtMensalidadeTitular;
    // End of variables declaration//GEN-END:variables
}
