/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OutrasInterfaces;

import Classes.Configuracao;
import Classes.Titular;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TURUGO
 */
public class ControlePagamento extends javax.swing.JFrame {

    /**
     * Creates new form ControlePagamento
     */
    public ControlePagamento() {
        initComponents();
        DefaultTableModel dtm = (DefaultTableModel) tableControlePagamento.getModel();
        
        for (int i = 0; i < Titular.titular.size(); i++) {
            if((Titular.titular.get(i).isQuitacao()==false) &&
               (Titular.titular.get(i).isSituacao()==true))
                dtm.addRow(new Object[]{Titular.titular.get(i).getCodAssociado(),Titular.titular.get(i).getNome(),Titular.titular.get(i).getCpf()
            });
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableControlePagamento = new javax.swing.JTable();
        btnRegistrarPagamento = new javax.swing.JButton();
        txtBuscaNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscaCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle Pagamento");
        setResizable(false);

        tableControlePagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "CPF"
            }
        ));
        tableControlePagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableControlePagamentoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableControlePagamento);

        btnRegistrarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Informação.png"))); // NOI18N
        btnRegistrarPagamento.setText("Registrar pagamento de mensalidade");
        btnRegistrarPagamento.setEnabled(false);
        btnRegistrarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagamentoActionPerformed(evt);
            }
        });

        txtBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por Nome:");

        jLabel2.setText("Buscar por CPF:");

        txtBuscaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaCPFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("*A busca diferencia letras maiúsculas de minúsculas");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegistrarPagamento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarPagamento)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagamentoActionPerformed
        float valor = 0;
        Object obj = tableControlePagamento.getModel().getValueAt(tableControlePagamento.getSelectedRow() ,0);
        String str = String.valueOf(obj);
        int id = Integer.parseInt(str);
        int posicao = 0;
        
        for(int i = 0; i < Titular.titular.size(); i++){
                if(Titular.titular.get(i).getCodAssociado()==id){
                        posicao = i;
                    }
                }

        for(int i=0; i<Titular.titular.get(posicao).codDependente.size();i++){
            valor = valor + Configuracao.getTaxaDependente();
        }
        
        valor = valor + Configuracao.getMensalidadeTitular();
        
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente efetuar o registro?\nValor a se pagar: R$ "+valor, "Pergunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
            Titular.titular.get(posicao).setQuitacao(true);
        }
        
        DefaultTableModel dtm = (DefaultTableModel) tableControlePagamento.getModel();
        
        ((DefaultTableModel) tableControlePagamento.getModel()).setRowCount(0);
        
        for (int i = 0; i < Titular.titular.size(); i++) {
            if(Titular.titular.get(i).isQuitacao()==false)
                dtm.addRow(new Object[]{Titular.titular.get(i).getCodAssociado(),Titular.titular.get(i).getNome(),Titular.titular.get(i).getCpf()
            });
        
        }
    }//GEN-LAST:event_btnRegistrarPagamentoActionPerformed

    private void tableControlePagamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableControlePagamentoMouseReleased
        btnRegistrarPagamento.setEnabled(true);
    }//GEN-LAST:event_tableControlePagamentoMouseReleased

    private void txtBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaNomeActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tableControlePagamento.getModel();
        
        ((DefaultTableModel) tableControlePagamento.getModel()).setRowCount(0);
        
        String txt = txtBuscaNome.getText();
        
        for (int i = 0; i < Titular.titular.size(); i++) {
            
            if((Titular.titular.get(i).isQuitacao()==false)&&
               (Titular.titular.get(i).getNome().contains(txt))==true&&
                (Titular.titular.get(i).isSituacao()==true))
                dtm.addRow(new Object[]{Titular.titular.get(i).getCodAssociado(),Titular.titular.get(i).getNome(),
                                        Titular.titular.get(i).getCpf()});

        }
        
    }//GEN-LAST:event_txtBuscaNomeActionPerformed

    private void txtBuscaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaCPFActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tableControlePagamento.getModel();
        
        ((DefaultTableModel) tableControlePagamento.getModel()).setRowCount(0);
        
        String txt = txtBuscaCPF.getText();
        
        for (int i = 0; i < Titular.titular.size(); i++) {
            if((Titular.titular.get(i).isQuitacao()==false)&&(
               Titular.titular.get(i).getCpf().contains(txt)==true)&&
                    (Titular.titular.get(i).isSituacao()==true))
                dtm.addRow(new Object[]{Titular.titular.get(i).getCodAssociado(),Titular.titular.get(i).getNome(),Titular.titular.get(i).getCpf()
            });
        
        }

    }//GEN-LAST:event_txtBuscaCPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlePagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableControlePagamento;
    private javax.swing.JTextField txtBuscaCPF;
    private javax.swing.JTextField txtBuscaNome;
    // End of variables declaration//GEN-END:variables
}
